export { default as Curricula } from './Curricula'
export { default as CurriculaDetails } from './CurriculaDetails'
// export { default as FeedBacks } from './Feedbacks'
export { default as Students } from './Students'
export { default as StudentDetails } from './StudentDetail'
export { default as Groups } from './Groups'
export { default as GroupDetails } from './GroupDetails'
export { default as Lectures } from './Lectures'
export { default as Dashboard } from './Dashboard'
